# Generated by Django 5.2.5 on 2025-09-05 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_customer_delivery_confirmed_and_more'),
        ('stores', '0006_alter_storestaff_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('on_break', 'On Break'), ('busy', 'Busy')], default='offline', max_length=10)),
                ('is_available', models.BooleanField(default=False)),
                ('max_concurrent_orders', models.PositiveIntegerField(default=3)),
                ('service_area_radius', models.PositiveIntegerField(default=10, help_text='Service radius in km')),
                ('vehicle_type', models.CharField(choices=[('bicycle', 'Bicycle'), ('scooter', 'Scooter'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van')], default='scooter', max_length=15)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_new_agents', to='stores.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_new_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Agent',
                'verbose_name_plural': 'Delivery Agents',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('at_store', 'At Store'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='assigned', max_length=15)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('agent_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_store_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('store_pickup_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('customer_delivery_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('store_pickup_verified', models.BooleanField(default=False)),
                ('customer_delivery_verified', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='delivery_new.deliveryagent')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.CharField(choices=[('delay', 'Delivery Delay'), ('damage', 'Package Damage'), ('location', 'Wrong Location'), ('customer', 'Customer Unavailable'), ('traffic', 'Traffic Issues'), ('vehicle', 'Vehicle Problems'), ('weather', 'Bad Weather'), ('other', 'Other Issue')], max_length=20)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='delivery_new.delivery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='delivery_new.delivery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='delivery_new.delivery')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
