# Generated by Django 5.2.5 on 2025-09-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=40.0, help_text='Base delivery fee in ₹', max_digits=10)),
                ('fee_per_km', models.DecimalField(decimal_places=2, default=5.0, help_text='Additional fee per km in ₹', max_digits=5)),
                ('minimum_delivery_fee', models.DecimalField(decimal_places=2, default=30.0, help_text='Minimum delivery fee in ₹', max_digits=10)),
                ('maximum_delivery_fee', models.DecimalField(decimal_places=2, default=150.0, help_text='Maximum delivery fee in ₹', max_digits=10)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Fixed Rate'), ('distance', 'Distance-Based'), ('order_value', 'Order Value-Based')], default='fixed', help_text='Method to calculate delivery fees', max_length=20)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=500.0, help_text='Order value above which delivery is free in ₹', max_digits=10)),
                ('agent_payout_percentage', models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage of delivery fee paid to agent', max_digits=5)),
            ],
            options={
                'verbose_name': 'Delivery Settings',
                'verbose_name_plural': 'Delivery Settings',
            },
        ),
    ]
