# Generated by Django 5.2.5 on 2025-09-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loyaltyconfiguration_promotionalbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('store_owner', 'Store Owner'), ('delivery_agent', 'Delivery Agent'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
