# Generated by Django 5.2.5 on 2025-09-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_storestaff_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storestaff',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storestaff',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storestaff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='store',
            name='staff_members',
        ),
        migrations.DeleteModel(
            name='StaffOrderAssignment',
        ),
        migrations.DeleteModel(
            name='StoreStaff',
        ),
    ]
